# Site settings
author: Oliver Feher
title: Oliver's matrix
header-img: img/home-bg.png
email: olcsee@gmail.com
copyright_name: Oliver Feher
description: > # this means to ignore newlines until "baseurl:"
  Oliver's experiences and ideas about every aspect of IT
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  oliverfeher

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
